name: Server Deploy to Oracle Cloud

on:
  push:
    paths:
      - 'server/**' # server 폴더 변경 시에만 작동

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master # SSH 접속용 오픈소스
        with:
          host: ${{ secrets.HOST }} # Oracle Cloud IP
          username: ubuntu # 우분투 계정명
          key: ${{ secrets.SSH_KEY }} # SSH 개인키
          script: |
            cd ~/WorshipLog/server
            git pull origin dev
            npm install
            npx prisma generate
            npm run build
            pm2 restart worshiplog-server
